Update patch set 4
Patch Set 4:

And additionally getting this errors
(Reverting this commit fixes it)

./scripts/gcc-version.sh: Zeile 31: printf: OSError:: Ungültige Zahl.
./scripts/gcc-version.sh: Zeile 31: printf: [Errno: Ungültige Zahl.
./scripts/gcc-version.sh: Zeile 31: printf: 2]: Ungültige Zahl.
./scripts/gcc-version.sh: Zeile 31: printf: No: Ungültige Zahl.
./scripts/gcc-version.sh: Zeile 31: printf: such: Ungültige Zahl.
./scripts/gcc-version.sh: Zeile 31: printf: file: Ungültige Zahl.
./scripts/gcc-version.sh: Zeile 31: printf: or: Ungültige Zahl.
./scripts/gcc-version.sh: Zeile 31: printf: directory: Ungültige Zahl.
./scripts/gcc-version.sh: Zeile 31: printf: OSError:: Ungültige Zahl.
./scripts/gcc-version.sh: Zeile 31: printf: [Errno: Ungültige Zahl.
./scripts/gcc-version.sh: Zeile 31: printf: 2]: Ungültige Zahl.
./scripts/gcc-version.sh: Zeile 31: printf: No: Ungültige Zahl.
./scripts/gcc-version.sh: Zeile 31: printf: such: Ungültige Zahl.
./scripts/gcc-version.sh: Zeile 31: printf: file: Ungültige Zahl.
./scripts/gcc-version.sh: Zeile 31: printf: or: Ungültige Zahl.
./scripts/gcc-version.sh: Zeile 31: printf: directory: Ungültige Zahl.
/bin/sh: 1: [: 0000: unexpected operator
Android GCC has been deprecated in favor of Clang, and will be removed from
Android in 2020-01 as per the deprecation plan in:
https://android.googlesource.com/platform/prebuilts/clang/host/linux-x86/+/master/GCC_4_9_DEPRECATION.md


Traceback (most recent call last):
  File "/media/martin/extLinux/developer/android/sonyTWRP/android_device_sony_tama_stock_twrp/tools/stock_kernel/aarch64-linux-android-4.9/bin/aarch64-linux-android-gcc", line 75, in <module>
    main(sys.argv)
  File "/media/martin/extLinux/developer/android/sonyTWRP/android_device_sony_tama_stock_twrp/tools/stock_kernel/aarch64-linux-android-4.9/bin/aarch64-linux-android-gcc", line 72, in main
    cw.invoke_compiler()
  File "/media/martin/extLinux/developer/android/sonyTWRP/android_device_sony_tama_stock_twrp/tools/stock_kernel/aarch64-linux-android-4.9/bin/aarch64-linux-android-gcc", line 67, in invoke_compiler
    os.execv(self.argv0, self.execargs)
OSError: [Errno 2] No such file or directory
Android GCC has been deprecated in favor of Clang, and will be removed from
Android in 2020-01 as per the deprecation plan in:
https://android.googlesource.com/platform/prebuilts/clang/host/linux-x86/+/master/GCC_4_9_DEPRECATION.md


Traceback (most recent call last):
  File "/media/martin/extLinux/developer/android/sonyTWRP/android_device_sony_tama_stock_twrp/tools/stock_kernel/aarch64-linux-android-4.9/bin/aarch64-linux-android-gcc", line 75, in <module>
    main(sys.argv)
  File "/media/martin/extLinux/developer/android/sonyTWRP/android_device_sony_tama_stock_twrp/tools/stock_kernel/aarch64-linux-android-4.9/bin/aarch64-linux-android-gcc", line 72, in main
    cw.invoke_compiler()
  File "/media/martin/extLinux/developer/android/sonyTWRP/android_device_sony_tama_stock_twrp/tools/stock_kernel/aarch64-linux-android-4.9/bin/aarch64-linux-android-gcc", line 67, in invoke_compiler
    os.execv(self.argv0, self.execargs)
OSError: [Errno 2] No such file or directory
Android GCC has been deprecated in favor of Clang, and will be removed from
Android in 2020-01 as per the deprecation plan in:
https://android.googlesource.com/platform/prebuilts/clang/host/linux-x86/+/master/GCC_4_9_DEPRECATION.md


Traceback (most recent call last):
  File "/media/martin/extLinux/developer/android/sonyTWRP/android_device_sony_tama_stock_twrp/tools/stock_kernel/aarch64-linux-android-4.9/bin/aarch64-linux-android-gcc", line 75, in <module>
    main(sys.argv)
  File "/media/martin/extLinux/developer/android/sonyTWRP/android_device_sony_tama_stock_twrp/tools/stock_kernel/aarch64-linux-android-4.9/bin/aarch64-linux-android-gcc", line 72, in main
    cw.invoke_compiler()
  File "/media/martin/extLinux/developer/android/sonyTWRP/android_device_sony_tama_stock_twrp/tools/stock_kernel/aarch64-linux-android-4.9/bin/aarch64-linux-android-gcc", line 67, in invoke_compiler
    os.execv(self.argv0, self.execargs)
OSError: [Errno 2] No such file or directory
Android GCC has been deprecated in favor of Clang, and will be removed from
Android in 2020-01 as per the deprecation plan in:
https://android.googlesource.com/platform/prebuilts/clang/host/linux-x86/+/master/GCC_4_9_DEPRECATION.md


Traceback (most recent call last):
  File "/media/martin/extLinux/developer/android/sonyTWRP/android_device_sony_tama_stock_twrp/tools/stock_kernel/aarch64-linux-android-4.9/bin/aarch64-linux-android-gcc", line 75, in <module>
    main(sys.argv)
  File "/media/martin/extLinux/developer/android/sonyTWRP/android_device_sony_tama_stock_twrp/tools/stock_kernel/aarch64-linux-android-4.9/bin/aarch64-linux-android-gcc", line 72, in main
    cw.invoke_compiler()
  File "/media/martin/extLinux/developer/android/sonyTWRP/android_device_sony_tama_stock_twrp/tools/stock_kernel/aarch64-linux-android-4.9/bin/aarch64-linux-android-gcc", line 67, in invoke_compiler
    os.execv(self.argv0, self.execargs)
OSError: [Errno 2] No such file or directory
Android GCC has been deprecated in favor of Clang, and will be removed from
Android in 2020-01 as per the deprecation plan in:
https://android.googlesource.com/platform/prebuilts/clang/host/linux-x86/+/master/GCC_4_9_DEPRECATION.md


Traceback (most recent call last):
  File "/media/martin/extLinux/developer/android/sonyTWRP/android_device_sony_tama_stock_twrp/tools/stock_kernel/aarch64-linux-android-4.9/bin/aarch64-linux-android-gcc", line 75, in <module>
    main(sys.argv)
  File "/media/martin/extLinux/developer/android/sonyTWRP/android_device_sony_tama_stock_twrp/tools/stock_kernel/aarch64-linux-android-4.9/bin/aarch64-linux-android-gcc", line 72, in main
    cw.invoke_compiler()
  File "/media/martin/extLinux/developer/android/sonyTWRP/android_device_sony_tama_stock_twrp/tools/stock_kernel/aarch64-linux-android-4.9/bin/aarch64-linux-android-gcc", line 67, in invoke_compiler
    os.execv(self.argv0, self.execargs)
OSError: [Errno 2] No such file or directory
Android GCC has been deprecated in favor of Clang, and will be removed from
Android in 2020-01 as per the deprecation plan in:
https://android.googlesource.com/platform/prebuilts/clang/host/linux-x86/+/master/GCC_4_9_DEPRECATION.md


Traceback (most recent call last):
  File "/media/martin/extLinux/developer/android/sonyTWRP/android_device_sony_tama_stock_twrp/tools/stock_kernel/aarch64-linux-android-4.9/bin/aarch64-linux-android-gcc", line 75, in <module>
    main(sys.argv)
  File "/media/martin/extLinux/developer/android/sonyTWRP/android_device_sony_tama_stock_twrp/tools/stock_kernel/aarch64-linux-android-4.9/bin/aarch64-linux-android-gcc", line 72, in main
    cw.invoke_compiler()
  File "/media/martin/extLinux/developer/android/sonyTWRP/android_device_sony_tama_stock_twrp/tools/stock_kernel/aarch64-linux-android-4.9/bin/aarch64-linux-android-gcc", line 67, in invoke_compiler
    os.execv(self.argv0, self.execargs)
OSError: [Errno 2] No such file or directory
./scripts/gcc-version.sh: Zeile 31: printf: OSError:: Ungültige Zahl.
./scripts/gcc-version.sh: Zeile 31: printf: [Errno: Ungültige Zahl.
./scripts/gcc-version.sh: Zeile 31: printf: 2]: Ungültige Zahl.
./scripts/gcc-version.sh: Zeile 31: printf: No: Ungültige Zahl.
./scripts/gcc-version.sh: Zeile 31: printf: such: Ungültige Zahl.
./scripts/gcc-version.sh: Zeile 31: printf: file: Ungültige Zahl.
./scripts/gcc-version.sh: Zeile 31: printf: or: Ungültige Zahl.
./scripts/gcc-version.sh: Zeile 31: printf: directory: Ungültige Zahl.
./scripts/gcc-version.sh: Zeile 31: printf: OSError:: Ungültige Zahl.
./scripts/gcc-version.sh: Zeile 31: printf: [Errno: Ungültige Zahl.
./scripts/gcc-version.sh: Zeile 31: printf: 2]: Ungültige Zahl.
./scripts/gcc-version.sh: Zeile 31: printf: No: Ungültige Zahl.
./scripts/gcc-version.sh: Zeile 31: printf: such: Ungültige Zahl.
./scripts/gcc-version.sh: Zeile 31: printf: file: Ungültige Zahl.
./scripts/gcc-version.sh: Zeile 31: printf: or: Ungültige Zahl.
./scripts/gcc-version.sh: Zeile 31: printf: directory: Ungültige Zahl.
/bin/sh: 1: [: 0000: unexpected operator
./scripts/gcc-version.sh: Zeile 31: printf: OSError:: Ungültige Zahl.
./scripts/gcc-version.sh: Zeile 31: printf: [Errno: Ungültige Zahl.
./scripts/gcc-version.sh: Zeile 31: printf: 2]: Ungültige Zahl.
./scripts/gcc-version.sh: Zeile 31: printf: No: Ungültige Zahl.
./scripts/gcc-version.sh: Zeile 31: printf: such: Ungültige Zahl.
./scripts/gcc-version.sh: Zeile 31: printf: file: Ungültige Zahl.
./scripts/gcc-version.sh: Zeile 31: printf: or: Ungültige Zahl.
./scripts/gcc-version.sh: Zeile 31: printf: directory: Ungültige Zahl.
./scripts/gcc-version.sh: Zeile 31: printf: OSError:: Ungültige Zahl.
./scripts/gcc-version.sh: Zeile 31: printf: [Errno: Ungültige Zahl.
./scripts/gcc-version.sh: Zeile 31: printf: 2]: Ungültige Zahl.
./scripts/gcc-version.sh: Zeile 31: printf: No: Ungültige Zahl.
./scripts/gcc-version.sh: Zeile 31: printf: such: Ungültige Zahl.
./scripts/gcc-version.sh: Zeile 31: printf: file: Ungültige Zahl.
./scripts/gcc-version.sh: Zeile 31: printf: or: Ungültige Zahl.
./scripts/gcc-version.sh: Zeile 31: printf: directory: Ungültige Zahl.
/bin/sh: 1: [: 0000: unexpected operator

Patch-set: 4